language: cpp
matrix:
  include:
    # Stable channel
    - os: linux
      env: TARGET=linux
    - os: osx
      env: TARGET=osx
script:
  - mkdir build && cd build && cmake -DBATCH_VERSION=ON .. && make
