language: cpp
matrix:
  include:
    # Stable channel
    - os: linux
      env: TARGET=linux
      dist: trusty
      sudo: required
      addons:
        apt:
          packages: pkg-config libyaml-cpp-dev libyaml-cpp0.5 cmake
    - os: osx
      env: TARGET=osx

before_install:
 - "if [ ${TRAVIS_OS_NAME} = 'osx' ]; then brew update && brew install pkg-config yaml-cpp cmake; fi"
script:
  - mkdir build && cd build && cmake -DBATCH_VERSION=ON .. && make
