language: cpp

git:
  depth: 1

matrix:
  include:
    - os: linux
      dist: trusty
      env: TARGET=lnx
    - os: osx
      env: TARGET=mac

script:
  - mkdir build && cd build && cmake -DBATCH_VERSION=ON -DUSE_OPENJPEG=ON .. && make && cd -

before_deploy:
  - export DATE=`date +%-d-%b-%Y`
  - zip -j dcm2niix_${DATE}_${TARGET}.zip build/bin/*

deploy:
  provider: releases
  api_key:
    secure: a9OkpPxOVtaKye9VpB3hdA/FSIHY/kSXn/F+0AxHCH1sNOyF7J0Ljn7xqT7vgdxWkAWACTtzLYXVvSmcr7z2JwDm846LvLvz8zr6X0da1P3dg9wMpQ6/yz1n3OE3N7DQMYUNa4g6i79SarTlm08kMTFDSzsNsBleS0dDoJAS5vitZPp4kwOUqB8qpAoV4dzwN7HDVYARWodP+tYzxptbjeQAhuv6TglxSs0xM7gXG+QmSmOAdnJkBNkPkyItdMoUx0G2hjnbn3aJaaIeovlShdBapu2vyJNPQ2FktIjl6P+ng+iE9koifP5I87wExUBVrQDi/W8TJwnJ+DFjZQNF1ZagityNT+8aldVFc0BE8Uh0m6Tfqi4kxTDWgHED/yhjBuyuhTO6CGWAFx/YzhIW+AnEzju0prwuuguoDdlHpmsFF+QpRfqgN7vdwrHP+10/FBtZv8ul3GQB6G7lTIxvwNjrofQTm2vhV/JUjPPRXbxqOxR0wA1sbjESzMXE7tXcovFg83MgfgBQ5K/xSAKM8YyQ28hNSn5bocrUS4OR0gDgizVSwG6RxDs+SlUrAyLvIiVKQk4/upU6SGMFYGPlxpTybpp4qY5+hX1aiQK5z8pUVRcBY4f++BSIfLYEmW0TZgQ7eXiQXtMMDooX1VqcfJY1Rf+sFm0qwab8Mrl+DsU=
  file_glob: true
  file: dcm2niix*.zip
  skip_cleanup: true
  on:
    tags: true
