Options:
  isGz:             false
  isFlipY:          false
  isVerbose:        false
  isCreateBIDS:     false
  isOnlySingleFile: false

Files:
    -
      in_dir:           /path/to/first/file
      out_dir:          /path/to/output/directory
      filename:         dcemri
    -
      in_dir:           /path/to/second/file
      out_dir:          /path/to/output/directory
      filename:         fa3